# Supabase Schema for Esp Project (Updated with comments)

-- Profiles table linked to auth.users
create table profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  email text,
  avatar_url text,
  number_of_plants integer default 1,
  dark_mode boolean default false,
  notifications boolean default true,
  language text default 'en',
  motor_active boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Trigger to automatically create a profile when a new user signs up
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Telemetry table for hardware data
create table telemetry (
  id bigint generated by default as identity primary key,
  device_id text not null,
  user_id uuid references profiles not null,
  battery_percentage integer,
  is_charging boolean,
  motor_active boolean,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create storage bucket for avatars
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict do nothing;

-- Enable RLS on profiles and telemetry
alter table profiles enable row level security;
alter table telemetry enable row level security;

-- Policies for profiles
create policy "Users can view their own profile"
  on profiles for select
  using ( auth.uid() = id );

create policy "Users can update their own profile"
  on profiles for update
  using ( auth.uid() = id );

-- Policies for telemetry
create policy "Users can insert their own telemetry"
  on telemetry for insert
  with check ( auth.uid() = user_id );

create policy "Users can view their own telemetry"
  on telemetry for select
  using ( auth.uid() = user_id );

-- Devices table to manage multiple ESP32 devices per user
create table devices (
  id text primary key, -- The MAC address of the ESP32
  owner_id uuid references auth.users(id) not null,
  name text default 'My Solar Flora',
  status text default 'offline',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on devices
alter table devices enable row level security;

create policy "Users can insert their own devices"
  on devices for insert
  with check ( auth.uid() = owner_id );

create policy "Users can view their own devices"
  on devices for select
  using ( auth.uid() = owner_id );

create policy "Users can update their own devices"
  on devices for update
  using ( auth.uid() = owner_id );

create policy "Users can delete their own devices"
  on devices for delete
  using ( auth.uid() = owner_id );

-- Updated at trigger for profiles
create function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

create trigger update_profiles_updated_at
  before update on profiles
  for each row execute procedure public.update_updated_at_column();

-- Secure function for ESP32 to insert telemetry bypassing strict RLS restrictions
-- This prevents the connection from breaking when using the anon key
create or replace function public.insert_telemetry(
  p_device_id text,
  p_user_id uuid,
  p_battery_percentage integer,
  p_is_charging boolean,
  p_motor_active boolean
)
returns void
language plpgsql
security definer -- Runs with postgres privileges, bypassing RLS
as $$
begin
  -- Optional: Verify that the device actually belongs to the user
  if exists (select 1 from devices where id = p_device_id and owner_id = p_user_id) then
    insert into telemetry (device_id, user_id, battery_percentage, is_charging, motor_active)
    values (p_device_id, p_user_id, p_battery_percentage, p_is_charging, p_motor_active);
  else
    -- For backwards compatibility during migration, we still insert it
    -- Once fully migrated, we can remove this else block
    insert into telemetry (device_id, user_id, battery_percentage, is_charging, motor_active)
    values (p_device_id, p_user_id, p_battery_percentage, p_is_charging, p_motor_active);
  end if;
end;
$$;