# Supabase Schema for Esp Project (Updated with comments)

-- Profiles table linked to auth.users
create table profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  email text,
  avatar_url text,
  number_of_plants integer default 1,
  dark_mode boolean default false,
  notifications boolean default true,
  language text default 'en',
  motor_active boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Trigger to automatically create a profile when a new user signs up
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Telemetry table for hardware data
create table telemetry (
  id bigint generated by default as identity primary key,
  device_id text not null,
  user_id uuid references profiles not null,
  battery_percentage integer,
  is_charging boolean,
  motor_active boolean,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create storage bucket for avatars
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict do nothing;

-- Enable RLS on profiles and telemetry
alter table profiles enable row level security;
alter table telemetry enable row level security;

-- Policies for profiles
create policy "Users can view their own profile"
  on profiles for select
  using ( auth.uid() = id );

create policy "Users can update their own profile"
  on profiles for update
  using ( auth.uid() = id );

-- Policies for telemetry
create policy "Users can insert their own telemetry"
  on telemetry for insert
  with check ( auth.uid() = user_id );

create policy "Users can view their own telemetry"
  on telemetry for select
  using ( auth.uid() = user_id );

-- Updated at trigger for profiles
create function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

create trigger update_profiles_updated_at
  before update on profiles
  for each row execute procedure public.update_updated_at_column();